export const Products_Loaded = 'Products_Loaded'
export const Products_Loaded_VEGETABLE = 'Products_Loaded_VEGETABLE'
export const Products_Loaded_FRUIT = 'Products_Loaded_FRUIT'
export const Products_Loaded_FLOWER = 'Products_Loaded_FLOWER'
export const onMoreDetails = 'onMoreDetails'